name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: pnpm build

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: pnpm test:types

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: pnpm test:unit
