name: Publish

on:
  workflow_dispatch:
    inputs:
      npm_tag:
        description: 'npm tag to publish to'
        required: true

permissions:
  id-token: write

jobs:
  publish_snapshot:
    name: Publish
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: true # needed for git push

      - uses: ./.github/composites/setup
      - run: pnpm build

      - name: git configuration
        run: |
          git config --global user.name 'Dcousens Bot'
          git config --global user.email 'github+automation@dcousens.com'

      - run: pnpm build
      - name: npm publish
        run: pnpm publish --access=restricted --tag ${{ inputs.npm_tag }} --report-summary --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: git push
        run: |
          <pnpm-publish-summary.json jq -r '.publishedPackages.[] | .name + "@" + .version' | xargs -I {} git tag "{}"
          git push origin --tags
